from __future__ import annotations


EMAIL_IMAP_HOST = "imap.mail.ru"
EMAIL_IMAP_PORT = 993
EMAIL_IMAP_SSL = True
EMAIL_IMAP_VERIFY_SSL = True

EMAIL_SMTP_HOST = "smtp.mail.ru"
EMAIL_SMTP_PORT = 465
EMAIL_SMTP_SSL = True
EMAIL_SMTP_START_SSL = False
EMAIL_SMTP_VERIFY_SSL = True

EMAIL_ENABLE_ATTACHMENT_DOWNLOAD = True
EMAIL_SAVE_TO_SENT = True
EMAIL_SENT_FOLDER_NAME = "Sent"
EMAIL_ACCOUNT_NAME = "personal"

WEBDAV_ACCOUNT_NAME = "cloud"
WEBDAV_BASE_URL = "https://webdav.mail.ru/"
WEBDAV_DESCRIPTION = ""
WEBDAV_VERIFY_SSL = True
WEBDAV_ENABLE_FILE_DOWNLOAD = True
WEBDAV_ENABLE_FILE_UPLOAD = True

CALDAV_ACCOUNT_NAME = "CalDAV"
CALDAV_BASE_URL = "https://calendar.mail.ru/"
CALDAV_DESCRIPTION = ""
CALDAV_VERIFY_SSL = False
CALDAV_ENABLE_WRITE = True
CALDAV_USE_WELL_KNOWN_DISCOVERY = True
CALDAV_WELL_KNOWN_PATH = "/.well-known/caldav"
